# Generated by Django 4.0 on 2021-12-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
