# Generated by Django 4.0 on 2021-12-23 05:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(blank=True)),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('post_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('backend_repo', models.CharField(blank=True, max_length=100, null=True)),
                ('frontend_repo', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.account')),
            ],
        ),
    ]
